config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings
  resources :conversations do
    resources :messages
  end

  resources :bookings, only: [:new, :create]
  get '/support' => 'support#new'
  post '/support' => 'support#create'

  #get '/bookings/new' => 'bookings#new', as: 'new_booking'
  #post '/bookings'=> 'bookings#create'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :title, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :country_code, presence: true
  validates :country, presence: {
    message: -> (listing, data) { "No country for code: #{listing.country_code}" }
  }
  validates :bed_count, numericality: { greater_than: 0 }

  geocoded_by :full_address
  after_validation :geocode

  belongs_to :host, class_name: 'User'
  has_many :conversations

  def country
    ISO3166::Country.new(country_code.upcase)
  end

  def full_address
    return nil if country.nil?
    #[street_address, city, country.name].join(',') OR
    "#{street_address}, #{city}, #{country.name}"
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @new_booking = Booking.new(check_in_at: Date.today, listing_id: @listing.id)
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end
  
  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.host_id = current_user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /listings/1/edit
  def edit
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :street_address, :city, :country_code, :bed_count, :bedroom_count, :bathroom_count, :description, :night_fee_cents, :cleaning_fee_cents)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :listing_title %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, id: :listing_street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :listing_city %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.text_field :country_code, id: :listing_country_code %>
  </div>

  <div class="field">
    <%= form.label :bed_count %>
    <%= form.number_field :bed_count, id: :listing_bed_count %>
  </div>

  <div class="field">
    <%= form.label :bedroom_count %>
    <%= form.number_field :bedroom_count, id: :listing_bedroom_count %>
  </div>

  <div class="field">
    <%= form.label :bathroom_count %>
    <%= form.number_field :bathroom_count, id: :listing_bathroom_count %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description %>
  </div>

  <div class="field">
    <%= form.label :night_fee_cents %>
    <%= form.number_field :night_fee_cents, id: :listing_night_fee_cents %>
  </div>

  <div class="field">
    <%= form.label :cleaning_fee_cents %>
    <%= form.number_field :cleaning_fee_cents, id: :listing_cleaning_fee_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', listing_path %>
<nav>
  <% if user_signed_in? %>
    <%= link_to 'Edit account', edit_user_registration_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-light', method: :delete %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
</nav>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Street address</th>
      <th>City</th>
      <th>Country code</th>
      <th>Bed count</th>
      <th>Bedroom count</th>
      <th>Bathroom count</th>
      <th>Description</th>
      <th>Night fee</th>
      <th>Cleaning fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.street_address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.country_code %></td>
        <td><%= listing.bed_count %></td>
        <td><%= listing.bedroom_count %></td>
        <td><%= listing.bathroom_count %></td>
        <td><%= listing.description %></td>
        
        <!-- Show nightly fee as dollars -->
        <td><%= Money.new(listing.night_fee_cents.to_s, :aud).format(:with_currency => true) %></td>

        <!-- show cleaning fee as dollars %>-->
        <td><%= Money.new(listing.cleaning_fee_cents.to_s, :aud).format(:with_currency => true) %></td>
        
        <td><%= link_to 'Show', listing, class: 'btn btn-success btn-sm' %></td>

        <% if ((user_signed_in?) && (listing.host_id == current_user.id)) %>
          <td><%= link_to 'Edit', edit_listing_path(listing), class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path, class: 'btn btn-success btn-sm' %>
<nav>
  <% if user_signed_in? %>
    <%= link_to 'Edit account', edit_user_registration_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-light', method: :delete %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
</nav>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>
<nav>
  <% if user_signed_in? %>
    <%= link_to 'Edit account', edit_user_registration_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-light', method: :delete %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
</nav>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<h2>Book</h2>
<p>
  <%= format_cents_for_country @listing.night_fee_cents, @listing.country %> per night
</p>

<% if ((user_signed_in?) && (@listing.host_id != current_user.id)) %>
  <%= link_to 'Book', new_booking_path(listing_id: @listing.id), class: 'wide btn btn-warning' %>
  <%= link_to 'Message me', new_conversation_path(guest_id: current_user.id, listing_id: @listing.id), class: 'wide btn btn-success' %>
<% end %>
<p>
  <strong>Street address:</strong>
  <%= @listing.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country.name %>
</p>

<p>
  <strong>Coords</strong>
  <%= @listing.latitude %>, <%= @listing.longitude %> 
</p>

<p>
  <strong>Bed count:</strong>
  <%= @listing.bed_count %>
</p>

<p>
  <strong>Bedroom count:</strong>
  <%= @listing.bedroom_count %>
</p>

<p>
  <strong>Bathroom count:</strong>
  <%= @listing.bathroom_count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Night fee:</strong>
  <%= Money.new(@listing.night_fee_cents.to_s, :aud).format(:with_currency => true) %>
  <%#= format_cents_for_country @listing.night_fee_cents, @listing.country %>
</p>

<p>
  <strong>Cleaning fee:</strong>
  <%= Money.new(@listing.cleaning_fee_cents.to_s, :aud).format(:with_currency => true) %>
  <%#= format_cents_for_country @listing.cleaning_fee_cents, @listing.country %>
</p>

<% if ((user_signed_in?) && (@listing.host_id == current_user.id)) %>
  <%= link_to 'Edit', edit_listing_path(@listing) %>
  <%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back to listings', listings_path %>